# Generated by Django 5.2.1 on 2025-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
